# Generated by Django 3.2.6 on 2021-11-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_orarend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tantargy',
            name='hosszu',
            field=models.CharField(max_length=50),
        ),
    ]
