# Generated by Django 3.2.6 on 2021-09-13 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Felhasznalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('kulsos', models.BooleanField(default=False)),
                ('gyogy', models.BooleanField(default=False)),
                ('felmentett', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Felhasználó',
                'verbose_name_plural': 'Felhasználók',
            },
        ),
        migrations.CreateModel(
            name='Foglalkozas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20)),
                ('letszam', models.IntegerField()),
                ('egyik_nev', models.CharField(max_length=50)),
                ('egyik_mettol', models.DurationField()),
                ('egyik_meddig', models.DurationField()),
                ('masik_nev', models.CharField(max_length=50)),
                ('masik_mettol', models.DurationField()),
                ('masik_meddig', models.DurationField()),
            ],
            options={
                'verbose_name': 'Foglalkozás',
                'verbose_name_plural': 'Foglalkozások',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nap',
                'verbose_name_plural': 'Napok',
            },
        ),
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(default='-', max_length=10)),
                ('kod', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Osztály',
                'verbose_name_plural': 'Osztályok',
            },
        ),
        migrations.CreateModel(
            name='Tipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50)),
                ('kod', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'Típus',
                'verbose_name_plural': 'Típusok',
            },
        ),
        migrations.CreateModel(
            name='Vezerlo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('kod', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vezerlő',
                'verbose_name_plural': 'Vezerlők',
            },
        ),
        migrations.CreateModel(
            name='Jelentkezes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('felhasznalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.felhasznalo')),
                ('foglalkozas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.foglalkozas')),
            ],
            options={
                'verbose_name': 'Jelentkezés',
                'verbose_name_plural': 'Jelentkezések',
            },
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='egyik_nap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egyik_nap', to='APP.nap'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='egyik_tanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egyik_tanar', to='APP.felhasznalo'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='masik_nap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masik_nap', to='APP.nap'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='masik_tanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masik_tanar', to='APP.felhasznalo'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='tipus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.tipus'),
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='osztaly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.osztaly'),
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
