# Generated by Django 3.2.6 on 2021-08-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_felhasznalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foglalkozas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50)),
                ('letszam', models.IntegerField()),
                ('mettol', models.DurationField()),
                ('meddig', models.DurationField()),
            ],
            options={
                'verbose_name': 'Foglalkozás',
                'verbose_name_plural': 'Foglalkozások',
            },
        ),
        migrations.CreateModel(
            name='Jelentkezes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foglalkozas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.foglalkozas')),
            ],
            options={
                'verbose_name': 'Jelentkezés',
                'verbose_name_plural': 'Jelentkezések',
            },
        ),
        migrations.CreateModel(
            name='Nap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nap',
                'verbose_name_plural': 'Napok',
            },
        ),
        migrations.CreateModel(
            name='Tipus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Típus',
                'verbose_name_plural': 'Típusok',
            },
        ),
        migrations.DeleteModel(
            name='Bigyo',
        ),
        migrations.RenameField(
            model_name='felhasznalo',
            old_name='ujtulajdonsag',
            new_name='nev',
        ),
        migrations.AddField(
            model_name='jelentkezes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.felhasznalo'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='nap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.nap'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='tanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.felhasznalo'),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='tipus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.tipus'),
        ),
    ]
