# Generated by Django 3.2.6 on 2021-08-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20210827_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jelentkezes',
            old_name='user',
            new_name='felhasznalo',
        ),
    ]
