# Generated by Django 3.2.6 on 2021-08-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_rename_user_jelentkezes_felhasznalo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipus',
            old_name='tipus',
            new_name='nev',
        ),
    ]
