# Generated by Django 3.2.6 on 2021-09-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_auto_20210913_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foglalkozas',
            old_name='egyik_nev',
            new_name='nev',
        ),
    ]
