# Generated by Django 3.2.6 on 2021-09-13 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_egyik_nev_foglalkozas_nev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foglalkozas',
            name='masik_nev',
        ),
    ]
