# Generated by Django 3.2.6 on 2021-09-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_remove_foglalkozas_masik_nev'),
    ]

    operations = [
        migrations.AddField(
            model_name='foglalkozas',
            name='e_nap',
            field=models.CharField(blank=True, choices=[('hetfo', 'Hétfő'), ('kedd', 'Kedd'), ('szerda', 'Szerda'), ('csutortok', 'Csütörtök'), ('pentek', 'Péntek'), ('szombat', 'Szombat'), ('vasarnap', 'Vasárnap')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='m_nap',
            field=models.CharField(blank=True, choices=[('hetfo', 'Hétfő'), ('kedd', 'Kedd'), ('szerda', 'Szerda'), ('csutortok', 'Csütörtök'), ('pentek', 'Péntek'), ('szombat', 'Szombat'), ('vasarnap', 'Vasárnap')], max_length=10, null=True),
        ),
    ]
