# Generated by Django 3.2.6 on 2021-09-12 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_foglalkozas_kod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osztaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=10)),
                ('kod', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Osztály',
                'verbose_name_plural': 'Osztályok',
            },
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='osztaly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='APP.osztaly'),
        ),
    ]
