# Generated by Django 3.2.6 on 2021-09-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_auto_20210913_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foglalkozas',
            name='egyik_nap',
        ),
        migrations.RemoveField(
            model_name='foglalkozas',
            name='masik_nap',
        ),
    ]
