# Generated by Django 3.2.6 on 2021-09-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0009_auto_20210913_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foglalkozas',
            old_name='e_nap',
            new_name='egyik_nap',
        ),
        migrations.RenameField(
            model_name='foglalkozas',
            old_name='m_nap',
            new_name='masik_nap',
        ),
    ]
