# Generated by Django 3.2.6 on 2021-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_auto_20210913_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foglalkozas',
            name='egyik_tanar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='foglalkozas',
            name='masik_tanar',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foglalkozas',
            name='tipus',
            field=models.CharField(choices=[('dse', 'DSE'), ('nemdse', 'nem DSE')], default='nemdse', max_length=10),
        ),
    ]
