# Generated by Django 3.2.6 on 2021-09-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_auto_20210914_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foglalkozas',
            name='tipus',
            field=models.CharField(choices=[('dse', 'DSE'), ('nemdse', 'nem DSE')], default='-', max_length=10),
        ),
    ]
