# Generated by Django 3.2.6 on 2021-09-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_alter_foglalkozas_tipus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foglalkozas',
            name='tipus',
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='tipus_kod',
            field=models.CharField(choices=[('dse', 'dse'), ('nemdse', 'nemdse')], default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='foglalkozas',
            name='tipus_nev',
            field=models.CharField(choices=[('DSE', 'DSE'), ('nem DSE', 'nem DSE')], default='-', max_length=10),
        ),
    ]
