# Generated by Django 3.2.6 on 2021-09-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_auto_20210914_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='osztaly',
            name='sorszam',
            field=models.SmallIntegerField(default=0),
        ),
    ]
