# Generated by Django 4.0.2 on 2022-09-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_osztaly_sorszam'),
    ]

    operations = [
        migrations.AddField(
            model_name='felhasznalo',
            name='jogosultsagok',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
