# Generated by Django 4.0.2 on 2022-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_felhasznalo_jogosultsagok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='felhasznalo',
            name='jogosultsagok',
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='atjelentkezhet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='feljelentkezhet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='felhasznalo',
            name='lejelentkezhet',
            field=models.BooleanField(default=False),
        ),
    ]
